name: build and publish to github pages

on:
  push:
    branches: [ main ]

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: "build"
    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write
    uses: vishalmamidi/workflows/.github/workflows/build-gradle.yml@main
    secrets: inherit
