name: build and publish to github pages

on:
  push:
    branches: [ main ]

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  reusable-workflow:
    name: "reusable"
    uses: vishalmamidi/workflows/.github/workflows/build-gradle.yml@main
    with:
      deploy: false
