# quick checks for pull request

name: quick checks

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  repository-projects: write
  
jobs:
  quick-checks-unit:
    name: 🚨
    uses: vishalmamidi/workflows/.github/workflows/quick-checks-unit.yml@main
    secrets: inherit
