# quick checks for pull request

name: quick checks

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  quick-checks-unit:
    name: 🚨
    # permissions:
    #   contents: read
    permissions: write-all
    uses: vishalmamidi/workflows/.github/workflows/quick-checks-unit.yml@main
    secrets: inherit
